#version: "3.8"
#
#services:
#  db:
#    container_name: db_container
#    image: postgres:16.3-alpine
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=12345
#      - POSTGRES_DB=SWP
#    volumes:
#      - db:/var/lib/postgresql/data
#    networks:
#      - my-network
#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - db
#    ports:
#      - "85:80"
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
#      - PGADMIN_DEFAULT_PASSWORD=adminpassword
#    restart: unless-stopped
#
#  app:
#    container_name: swp391-api-container
#    image: swp391/swp391-be
#    depends_on:
#      - db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/SWP?serverTimezone=UTC&allowPublicKeyRetrieval=true
#      PGADMIN_USER: postgres
#      PGADMIN_PASSWORD: 12345
#
#    #    volumes:
#    #      - .m2:/root/.m2
#    #    stdin_open: true
#    #    tty: true
#    networks:
#      - my-network
#
#
#volumes:
#  db:
#networks:
#  my-network:
##    driver: bridge

version: '2'

services:
  app:
    container_name: swp391-api-container
    image: swp391/swp391-be
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres