version: "3.8"

services:
  db:
    container_name: db_container
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=swp391
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - my-network
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "85:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    restart: unless-stopped

  app:
    container_name: swp391-api-container
    image: swp391/swp391-be
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/swp391?serverTimezone=UTC&allowPublicKeyRetrieval=true
      PGADMIN_USER: postgres
      PGADMIN_PASSWORD: 12345

    #    volumes:
    #      - .m2:/root/.m2
    #    stdin_open: true
    #    tty: true
    networks:
      - my-network

volumes:
  db:
networks:
  my-network:
    driver: bridge